### ISSUE TITLE
Request - Slanted Aircraft Names in Matrix

### ISSUE THREAD

**Issue by MexterInfinite** [dantei-dev/Kneeboard-Manager-Releases#1]
Heya, quick feedback since I happened to find this today. It would be nice if the aircraft folder names in the Matrix are slanted 30-40 degrees so they are easier to read. It might require some extra effort to make sure it doesn't mess with scrolling though. Right now, it becomes a bit draining on the eyes to have to read the names sideways. Other than that minor gripe, I feel like this is a great lightweight way to organize groups of kneeboards for planes.

**Comment by dantei-dev** [comment]
Thanks for the feedback. 
I will see what I can do.

**Comment by dantei-dev** [comment]
![aircraft_label_slant_-30 small](https://github.com/user-attachments/assets/3ebfd3f8-943e-4fb8-a1f7-36e3a601bf7c)
![aircraft_label_slant_-15 small](https://github.com/user-attachments/assets/336de96c-2428-4a96-9495-6d8599382e65)
![aircraft_label_slant_+15 small](https://github.com/user-attachments/assets/90921e76-564d-4724-aae1-6d343aeab9dd)
![aircraft_label_slant_+30 small](https://github.com/user-attachments/assets/07c9f032-ddd2-44d9-bf2f-02cb0243f265)


It's not perfect.

But next release will have a configurable slant.

**Comment by MexterInfinite** [comment]
That seems good for readability even if the boxes don't move with it. Usability over aesthetics and all. Thanks for implementing it.

**Comment by dantei-dev** [comment]
![aircraft_label_slant_+30 small](https://github.com/user-attachments/assets/e5399733-55c9-4b02-9235-2471d8b440ef)
![aircraft_label_slant_+15 small](https://github.com/user-attachments/assets/72763d18-c60e-4deb-91c1-78722884a1c1)

New aircraft labels available with release [0.0.3](https://github.com/dantei-dev/Kneeboard-Manager-Releases/releases/tag/0.0.3).
